### ISSUE TITLE
Youtube download gets failed 403

### ISSUE THREAD

**Issue by vah7id** [JeffreyCA/spleeter-web#795]
Hi @JeffreyCA recently I'm getting 403 http bad request when I try to load a youtube URL! Would that be an issue from ytb-dl package? I tried to change my youtube API key but still get a same error!

**Comment by JeffreyCA** [comment]
Hi, is it failing for all links or certain ones? Can you share any logs from Docker?

**Comment by vah7id** [comment]
it fails for any URL when it tried to fetch! Search query feature works fine! here is the log:

`celery-fast_1  | [2023-09-23 11:17:50,181: WARNING/ForkPoolWorker-1] ERROR: unable to download video data: HTTP Error 403: Forbidden
2023-09-23 13:17:50 celery-fast_1  | [2023-09-23 11:17:50,181: WARNING/ForkPoolWorker-1] 
2023-09-23 13:17:50 celery-fast_1  | 
2023-09-23 13:17:50 celery-fast_1  | [2023-09-23 11:17:50,193: ERROR/ForkPoolWorker-1] Task api.tasks.fetch_youtube_audio[c24f7354-9882-4a69-8b0e-c768d5a44f1d] raised unexpected: DownloadError('ERROR: unable to download video data: HTTP Error 403: Forbidden')
2023-09-23 13:17:50 celery-fast_1  | Traceback (most recent call last):
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
2023-09-23 13:17:50 celery-fast_1  |     R = retval = fun(*args, **kwargs)
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
2023-09-23 13:17:50 celery-fast_1  |     return self.run(*args, **kwargs)
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 54, in run
2023-09-23 13:17:50 celery-fast_1  |     ret = task.retry(exc=exc, **retry_kwargs)
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 714, in retry
2023-09-23 13:17:50 celery-fast_1  |     raise_with_context(exc)
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 34, in run
2023-09-23 13:17:50 celery-fast_1  |     return task._orig_run(*args, **kwargs)
2023-09-23 13:17:50 celery-fast_1  |   File "/webapp/api/tasks.py", line 324, in fetch_youtube_audio
2023-09-23 13:17:50 celery-fast_1  |     raise error
2023-09-23 13:17:50 celery-fast_1  |   File "/webapp/api/tasks.py", line 288, in fetch_youtube_audio
2023-09-23 13:17:50 celery-fast_1  |     download_audio(link, rel_path)
2023-09-23 13:17:50 celery-fast_1  |   File "/webapp/api/youtubedl.py", line 115, in download_audio
2023-09-23 13:17:50 celery-fast_1  |     ydl.download([url])
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3349, in download
2023-09-23 13:17:50 celery-fast_1  |     self.__download_wrapper(self.extract_info)(
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3324, in wrapper
2023-09-23 13:17:50 celery-fast_1  |     res = func(*args, **kwargs)
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1491, in extract_info
2023-09-23 13:17:50 celery-fast_1  |     return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
2023-09-23 13:17:50 celery-fast_1  |     return func(self, *args, **kwargs)
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1599, in __extract_info
2023-09-23 13:17:50 celery-fast_1  |     return self.process_ie_result(ie_result, download, extra_info)
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1658, in process_ie_result
2023-09-23 13:17:50 celery-fast_1  |     ie_result = self.process_video_result(ie_result, download=download)
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2763, in process_video_result
2023-09-23 13:17:50 celery-fast_1  |     self.process_info(new_info)
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3236, in process_info
2023-09-23 13:17:50 celery-fast_1  |     self.report_error('unable to download video data: %s' % error_to_compat_str(err))
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1012, in report_error
2023-09-23 13:17:50 celery-fast_1  |     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
2023-09-23 13:17:50 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 952, in trouble
2023-09-23 13:17:50 celery-fast_1  |     raise DownloadError(message, exc_info)
2023-09-23 13:17:50 celery-fast_1  | yt_dlp.utils.DownloadError: ERROR: unable to download video data: HTTP Error 403: Forbidden`

**Comment by vah7id** [comment]
@JeffreyCA based on this thread on ytb-dl issues page: [](https://github.com/yt-dlp/yt-dlp/issues/7594)
It seems updating to nightly should fixed the problem but don't know how we could do this in our repo!
`yt-dlp --update-to nightly`

**Comment by JeffreyCA** [comment]
Thanks, can you test the changes in the `ytdlp-fixes` branch (#796) by building from source and add the following to your `.env` file?

```
YOUTUBEDL_SOURCE_ADDR=0.0.0.0
YOUTUBEDL_VERBOSE=1
```

I updated the package to latest version and saw on the yt-dlp issue that forcing IPv4 worked for some people

**Comment by vah7id** [comment]
it fails now with this error:
'Settings' object has no attribute 'YOUTUBEDL_SOURCE_ADDR'  in youtubedl.py
`
Task api.tasks.fetch_youtube_audio[4189bd4d-6380-4456-89b8-3f57d20e168e] raised unexpected: AttributeError("'Settings' object has no attribute 'YOUTUBEDL_SOURCE_ADDR'")
2023-09-23 20:12:27 celery-fast_1  | Traceback (most recent call last):
`

**Comment by vah7id** [comment]
@JeffreyCA  I set the verbose an source address manually to 0.0.0.0 and 1 and here is the log (still getting the http 403 error)

`

2023-09-23 20:37:36 celery-fast_1  | [2023-09-23 18:37:36,444: WARNING/ForkPoolWorker-1] ERROR: unable to download video data: HTTP Error 403: Forbidden
2023-09-23 20:37:36 celery-fast_1  | [2023-09-23 18:37:36,444: WARNING/ForkPoolWorker-1] 
2023-09-23 20:37:36 celery-fast_1  | 
2023-09-23 20:37:36 celery-fast_1  | [2023-09-23 18:37:36,456: INFO/MainProcess] Task api.tasks.fetch_youtube_audio[d6291d04-7a6a-48c3-9618-c2e24a42e052] received
2023-09-23 20:37:36 celery-fast_1  | [2023-09-23 18:37:36,460: INFO/ForkPoolWorker-1] Task api.tasks.fetch_youtube_audio[d6291d04-7a6a-48c3-9618-c2e24a42e052] retry: Retry in 3s: DownloadError('ERROR: unable to download video data: HTTP Error 403: Forbidden')
2023-09-23 20:37:36 celery-fast_1  | [2023-09-23 18:37:36,465: ERROR/MainProcess] Task handler raised error: <MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: Retry(Retry(...), DownloadError('ERROR: unable to download video data: HTTP Error 403: Forbidden'), 3)>, None)"'. Reason: ''TypeError("cannot pickle \'_io.BufferedReader\' object")''.>
2023-09-23 20:37:36 celery-fast_1  | Traceback (most recent call last):
2023-09-23 20:37:36 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/billiard/pool.py", line 366, in workloop
2023-09-23 20:37:36 celery-fast_1  |     put((READY, (job, i, result, inqW_fd)))
2023-09-23 20:37:36 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/billiard/queues.py", line 366, in put
2023-09-23 20:37:36 celery-fast_1  |     self.send_payload(ForkingPickler.dumps(obj))
2023-09-23 20:37:36 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/billiard/reduction.py", line 56, in dumps
2023-09-23 20:37:36 celery-fast_1  |     cls(buf, protocol).dump(obj)
2023-09-23 20:37:36 celery-fast_1  | billiard.pool.MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: Retry(Retry(...), DownloadError('ERROR: unable to download video data: HTTP Error 403: Forbidden'), 3)>, None)"'. Reason: ''TypeError("cannot pickle \'_io.BufferedReader\' object")''.
2023-09-23 20:37:37 api_1          | [23/Sep/2023 18:37:37] "GET /api/source-track/be06b682-aee0-48e4-8a76-0597fcb5738d/ HTTP/1.1" 200 334
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,537: WARNING/ForkPoolWorker-1] eef8fc18-2eeb-4790-8981-44328d079e08
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,537: WARNING/ForkPoolWorker-1] 
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,539: WARNING/ForkPoolWorker-1] https://www.youtube.com/watch?v=5qm8PH4xAss14315
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,540: WARNING/ForkPoolWorker-1] 
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,544: WARNING/ForkPoolWorker-1] debuggggg1211###3######################################
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,545: WARNING/ForkPoolWorker-1] 
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,546: WARNING/ForkPoolWorker-1] media
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,547: WARNING/ForkPoolWorker-1] 
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,547: WARNING/ForkPoolWorker-1] separate
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,548: WARNING/ForkPoolWorker-1] 
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,548: WARNING/ForkPoolWorker-1] uploads
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,548: WARNING/ForkPoolWorker-1] 
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,549: WARNING/ForkPoolWorker-1] eef8fc18-2eeb-4790-8981-44328d079e08
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,549: WARNING/ForkPoolWorker-1] 
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,550: WARNING/ForkPoolWorker-1] eef8fc18-2eeb-4790-8981-44328d079e08
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,551: WARNING/ForkPoolWorker-1] 
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,552: WARNING/ForkPoolWorker-1] debuggggg1211###3######################################
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,552: WARNING/ForkPoolWorker-1] 
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,554: WARNING/ForkPoolWorker-1] [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out missing (LoggingProxy) (No ANSI), error missing (LoggingProxy) (No ANSI), screen missing (LoggingProxy) (No ANSI)
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,554: WARNING/ForkPoolWorker-1] [debug] yt-dlp version 2023.01.06 [6becd2508] API
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,555: WARNING/ForkPoolWorker-1] [debug] params: {'format': 'bestaudio/best', 'forcefilename': True, 'noplaylist': True, 'source_address': '0.0.0.0', 'verbose': 1, 'compat_opts': set()}
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,555: WARNING/ForkPoolWorker-1] [debug] Lazy loading extractors is disabled
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,556: WARNING/ForkPoolWorker-1] [debug] Python 3.8.16 (CPython x86_64 64bit) - Linux-5.15.49-linuxkit-x86_64-with-glibc2.2.5 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,601: WARNING/ForkPoolWorker-1] [debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,603: WARNING/ForkPoolWorker-1] [debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,614: WARNING/ForkPoolWorker-1] [debug] Proxy map: {}
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,698: WARNING/ForkPoolWorker-1] [debug] Loaded 1767 extractors
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,701: WARNING/ForkPoolWorker-1] [youtube] Extracting URL: https://www.youtube.com/watch?v=5qm8PH4xAss
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:39 celery-fast_1  | [2023-09-23 18:37:39,702: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading webpage
2023-09-23 20:37:39 celery-fast_1  | 
2023-09-23 20:37:40 celery-fast_1  | [2023-09-23 18:37:40,043: WARNING/ForkPoolWorker-1] WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-09-23 20:37:40 celery-fast_1  | 
2023-09-23 20:37:40 celery-fast_1  | [2023-09-23 18:37:40,046: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading android player API JSON
2023-09-23 20:37:40 celery-fast_1  | 
2023-09-23 20:37:40 celery-fast_1  | [2023-09-23 18:37:40,227: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading iframe API JS
2023-09-23 20:37:40 celery-fast_1  | 
2023-09-23 20:37:40 celery-fast_1  | [2023-09-23 18:37:40,376: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading player 9cbb6b90
2023-09-23 20:37:40 celery-fast_1  | 
2023-09-23 20:37:40 celery-fast_1  | [2023-09-23 18:37:40,652: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading web player API JSON
2023-09-23 20:37:40 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,010: WARNING/ForkPoolWorker-1] WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,012: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading initial data API JSON
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,871: WARNING/ForkPoolWorker-1] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,871: WARNING/ForkPoolWorker-1] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,902: WARNING/ForkPoolWorker-1] [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out missing (LoggingProxy) (No ANSI), error missing (LoggingProxy) (No ANSI), screen missing (LoggingProxy) (No ANSI)
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,903: WARNING/ForkPoolWorker-1] [debug] yt-dlp version 2023.01.06 [6becd2508] API
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,903: WARNING/ForkPoolWorker-1] [debug] params: {'format': 'bestaudio/best', 'forcefilename': True, 'outtmpl': 'media/uploads/eef8fc18-2eeb-4790-8981-44328d079e08/50 Cent - In Da Club.webm', 'cachedir': False, 'noplaylist': True, 'source_address': '0.0.0.0', 'verbose': 1, 'compat_opts': set()}
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,903: WARNING/ForkPoolWorker-1] [debug] Lazy loading extractors is disabled
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,904: WARNING/ForkPoolWorker-1] [debug] Python 3.8.16 (CPython x86_64 64bit) - Linux-5.15.49-linuxkit-x86_64-with-glibc2.2.5 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,950: WARNING/ForkPoolWorker-1] [debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,952: WARNING/ForkPoolWorker-1] [debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:41 celery-fast_1  | [2023-09-23 18:37:41,961: WARNING/ForkPoolWorker-1] [debug] Proxy map: {}
2023-09-23 20:37:41 celery-fast_1  | 
2023-09-23 20:37:42 celery-fast_1  | [2023-09-23 18:37:42,048: WARNING/ForkPoolWorker-1] [debug] Loaded 1767 extractors
2023-09-23 20:37:42 celery-fast_1  | 
2023-09-23 20:37:42 celery-fast_1  | [2023-09-23 18:37:42,051: WARNING/ForkPoolWorker-1] [youtube] Extracting URL: https://www.youtube.com/watch?v=5qm8PH4xAss
2023-09-23 20:37:42 celery-fast_1  | 
2023-09-23 20:37:42 celery-fast_1  | [2023-09-23 18:37:42,052: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading webpage
2023-09-23 20:37:42 celery-fast_1  | 
2023-09-23 20:37:42 celery-fast_1  | [2023-09-23 18:37:42,433: WARNING/ForkPoolWorker-1] WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-09-23 20:37:42 celery-fast_1  | 
2023-09-23 20:37:42 celery-fast_1  | [2023-09-23 18:37:42,435: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading android player API JSON
2023-09-23 20:37:42 celery-fast_1  | 
2023-09-23 20:37:42 celery-fast_1  | [2023-09-23 18:37:42,620: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading iframe API JS
2023-09-23 20:37:42 celery-fast_1  | 
2023-09-23 20:37:42 celery-fast_1  | [2023-09-23 18:37:42,796: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading player 9cbb6b90
2023-09-23 20:37:42 celery-fast_1  | 
2023-09-23 20:37:43 celery-fast_1  | [2023-09-23 18:37:43,048: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading web player API JSON
2023-09-23 20:37:43 celery-fast_1  | 
2023-09-23 20:37:43 celery-fast_1  | [2023-09-23 18:37:43,392: WARNING/ForkPoolWorker-1] WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-09-23 20:37:43 celery-fast_1  | 
2023-09-23 20:37:43 celery-fast_1  | [2023-09-23 18:37:43,393: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading initial data API JSON
2023-09-23 20:37:43 celery-fast_1  | 
2023-09-23 20:37:44 celery-fast_1  | [2023-09-23 18:37:44,241: WARNING/ForkPoolWorker-1] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
2023-09-23 20:37:44 celery-fast_1  | 
2023-09-23 20:37:44 celery-fast_1  | [2023-09-23 18:37:44,242: WARNING/ForkPoolWorker-1] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
2023-09-23 20:37:44 celery-fast_1  | 
2023-09-23 20:37:44 celery-fast_1  | [2023-09-23 18:37:44,287: WARNING/ForkPoolWorker-1] [youtube] Extracting URL: https://www.youtube.com/watch?v=5qm8PH4xAss
2023-09-23 20:37:44 celery-fast_1  | 
2023-09-23 20:37:44 celery-fast_1  | [2023-09-23 18:37:44,288: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading webpage
2023-09-23 20:37:44 celery-fast_1  | 
2023-09-23 20:37:44 celery-fast_1  | [2023-09-23 18:37:44,667: WARNING/ForkPoolWorker-1] WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-09-23 20:37:44 celery-fast_1  | 
2023-09-23 20:37:44 celery-fast_1  | [2023-09-23 18:37:44,673: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading android player API JSON
2023-09-23 20:37:44 celery-fast_1  | 
2023-09-23 20:37:44 celery-fast_1  | [2023-09-23 18:37:44,854: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading iframe API JS
2023-09-23 20:37:44 celery-fast_1  | 
2023-09-23 20:37:45 celery-fast_1  | [2023-09-23 18:37:45,011: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading web player API JSON
2023-09-23 20:37:45 celery-fast_1  | 
2023-09-23 20:37:45 celery-fast_1  | [2023-09-23 18:37:45,380: WARNING/ForkPoolWorker-1] WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-09-23 20:37:45 celery-fast_1  | 
2023-09-23 20:37:45 celery-fast_1  | [2023-09-23 18:37:45,381: WARNING/ForkPoolWorker-1] [youtube] 5qm8PH4xAss: Downloading initial data API JSON
2023-09-23 20:37:45 celery-fast_1  | 
2023-09-23 20:37:46 celery-fast_1  | [2023-09-23 18:37:46,204: WARNING/ForkPoolWorker-1] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
2023-09-23 20:37:46 celery-fast_1  | 
2023-09-23 20:37:46 celery-fast_1  | [2023-09-23 18:37:46,204: WARNING/ForkPoolWorker-1] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
2023-09-23 20:37:46 celery-fast_1  | 
2023-09-23 20:37:46 celery-fast_1  | [2023-09-23 18:37:46,233: WARNING/ForkPoolWorker-1] [info] 5qm8PH4xAss: Downloading 1 format(s): 251
2023-09-23 20:37:46 celery-fast_1  | 
2023-09-23 20:37:46 celery-fast_1  | [2023-09-23 18:37:46,245: WARNING/ForkPoolWorker-1] media/uploads/eef8fc18-2eeb-4790-8981-44328d079e08/50 Cent - In Da Club.webm
2023-09-23 20:37:46 celery-fast_1  | 
2023-09-23 20:37:46 celery-fast_1  | [2023-09-23 18:37:46,258: WARNING/ForkPoolWorker-1] [debug] Invoking http downloader on "https://rr3---sn-1gi7znek.googlevideo.com/videoplayback?expire=1695515864&ei=eDAPZYuGOd7A6dsP_7qeiAw&ip=194.153.180.89&id=o-AJG1fwNfJAKqTElDN_2z98Fxmc4EFLabEF2Sau1e-zEe&itag=251&source=youtube&requiressl=yes&mh=bK&mm=31%2C26&mn=sn-1gi7znek%2Csn-hpa7knll&ms=au%2Conr&mv=m&mvi=3&pl=21&gcr=ch&initcwndbps=2797500&spc=UWF9fydb3ZDHnF5TQyj999HDgrxwlyAA2JlHk07TRQ&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3981052&dur=247.901&lmt=1694134273001232&mt=1695493754&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPI3igCxxS4GQoxVAoe7uV9ckf5iqcX61ucAC9I0GfgyAiA3-jJ-Dat7bpJlNZsFP8KF225r2JXbNPLkZkyyEA18-A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPK-KtreNXpnNa9qBm5aU-AHD13WxvFKrQ3Hq5UJBQiiAiEA7JHxAXgHRyApl7PZM0oMcNzkIbrtjU2ws9FADrFbz-s%3D"
2023-09-23 20:37:46 celery-fast_1  | 
2023-09-23 20:37:46 celery-fast_1  | [2023-09-23 18:37:46,374: WARNING/ForkPoolWorker-1] ERROR: unable to download video data: HTTP Error 403: Forbidden
2023-09-23 20:37:46 celery-fast_1  | 
2023-09-23 20:37:46 celery-fast_1  | [2023-09-23 18:37:46,375: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3227, in process_info
2023-09-23 20:37:46 celery-fast_1  |     success, real_download = self.dl(temp_filename, info_dict)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2950, in dl
2023-09-23 20:37:46 celery-fast_1  |     return fd.download(name, new_info, subtitle)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 444, in download
2023-09-23 20:37:46 celery-fast_1  |     ret = self.real_download(filename, info_dict)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 371, in real_download
2023-09-23 20:37:46 celery-fast_1  |     establish_connection()
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
2023-09-23 20:37:46 celery-fast_1  |     ctx.data = self.ydl.urlopen(request)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3721, in urlopen
2023-09-23 20:37:46 celery-fast_1  |     return self._opener.open(req, timeout=self._socket_timeout)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
2023-09-23 20:37:46 celery-fast_1  |     response = meth(req, response)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
2023-09-23 20:37:46 celery-fast_1  |     response = self.parent.error(
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
2023-09-23 20:37:46 celery-fast_1  |     return self._call_chain(*args)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
2023-09-23 20:37:46 celery-fast_1  |     result = func(*args)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
2023-09-23 20:37:46 celery-fast_1  |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2023-09-23 20:37:46 celery-fast_1  | urllib.error.HTTPError: HTTP Error 403: Forbidden
2023-09-23 20:37:46 celery-fast_1  | 
2023-09-23 20:37:46 celery-fast_1  | 
2023-09-23 20:37:46 celery-fast_1  | [2023-09-23 18:37:46,380: WARNING/ForkPoolWorker-1] ERROR: unable to download video data: HTTP Error 403: Forbidden
2023-09-23 20:37:46 celery-fast_1  | [2023-09-23 18:37:46,380: WARNING/ForkPoolWorker-1] 
2023-09-23 20:37:46 celery-fast_1  | 
2023-09-23 20:37:46 celery-fast_1  | [2023-09-23 18:37:46,396: ERROR/ForkPoolWorker-1] Task api.tasks.fetch_youtube_audio[d6291d04-7a6a-48c3-9618-c2e24a42e052] raised unexpected: DownloadError('ERROR: unable to download video data: HTTP Error 403: Forbidden')
2023-09-23 20:37:46 celery-fast_1  | Traceback (most recent call last):
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
2023-09-23 20:37:46 celery-fast_1  |     R = retval = fun(*args, **kwargs)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
2023-09-23 20:37:46 celery-fast_1  |     return self.run(*args, **kwargs)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 54, in run
2023-09-23 20:37:46 celery-fast_1  |     ret = task.retry(exc=exc, **retry_kwargs)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 714, in retry
2023-09-23 20:37:46 celery-fast_1  |     raise_with_context(exc)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/celery/app/autoretry.py", line 34, in run
2023-09-23 20:37:46 celery-fast_1  |     return task._orig_run(*args, **kwargs)
2023-09-23 20:37:46 celery-fast_1  |   File "/webapp/api/tasks.py", line 324, in fetch_youtube_audio
2023-09-23 20:37:46 celery-fast_1  |     raise error
2023-09-23 20:37:46 celery-fast_1  |   File "/webapp/api/tasks.py", line 288, in fetch_youtube_audio
2023-09-23 20:37:46 celery-fast_1  |     download_audio(link, rel_path)
2023-09-23 20:37:46 celery-fast_1  |   File "/webapp/api/youtubedl.py", line 120, in download_audio
2023-09-23 20:37:46 celery-fast_1  |     ydl.download([url])
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3349, in download
2023-09-23 20:37:46 celery-fast_1  |     self.__download_wrapper(self.extract_info)(
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3324, in wrapper
2023-09-23 20:37:46 celery-fast_1  |     res = func(*args, **kwargs)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1491, in extract_info
2023-09-23 20:37:46 celery-fast_1  |     return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
2023-09-23 20:37:46 celery-fast_1  |     return func(self, *args, **kwargs)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1599, in __extract_info
2023-09-23 20:37:46 celery-fast_1  |     return self.process_ie_result(ie_result, download, extra_info)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1658, in process_ie_result
2023-09-23 20:37:46 celery-fast_1  |     ie_result = self.process_video_result(ie_result, download=download)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2763, in process_video_result
2023-09-23 20:37:46 celery-fast_1  |     self.process_info(new_info)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3236, in process_info
2023-09-23 20:37:46 celery-fast_1  |     self.report_error('unable to download video data: %s' % error_to_compat_str(err))
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1012, in report_error
2023-09-23 20:37:46 celery-fast_1  |     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
2023-09-23 20:37:46 celery-fast_1  |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 952, in trouble
2023-09-23 20:37:46 celery-fast_1  |     raise DownloadError(message, exc_info)
2023-09-23 20:37:46 celery-fast_1  | yt_dlp.utils.DownloadError: ERROR: unable to download video data: HTTP Error 403: Forbidden
`

**Comment by JeffreyCA** [comment]
Can you try the latest yt-dlp nightly build from yt-dlp repo, does that work?

**Comment by vah7id** [comment]
@JeffreyCA The previous solution worked out after I hardcoded the YOUTUBEDL_SOURCE_ADDR=0.0.0.0 and verbose: 1 on production but on local wasn't working! So no need to try the nightly build! 👍 Appreciate your help!!

**Comment by JeffreyCA** [comment]
Thanks for the update. Was there any difference in how you configured or started Spleeter Web locally vs in prod?
